# Use the Ubuntu 16 ("Xenial") container as a base image.
FROM ubuntu:xenial

# Install essential dependencies for Ansible and testing our project.
RUN apt-get update --yes && apt-get dist-upgrade --yes \
    && apt-get install --yes \
    software-properties-common \
    git \
    netcat \
    systemd \
    && rm -rf /var/lib/apt/lists/*

# Install Ansible inside the container.
RUN apt-add-repository --yes ppa:ansible/ansible \
    && apt-get update --yes && apt-get install --yes \
    ansible \
    && rm -rf /var/lib/apt/lists/*

# Create a default Ansible inventory hosts file.
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Run systemd when `docker run` is executed.
ENTRYPOINT ["/bin/systemd"]
